-- MySQL Script generated by MySQL Workbench
-- Mon May 12 08:49:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema init
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema init
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `init` DEFAULT CHARACTER SET utf8 ;
USE `init` ;

-- -----------------------------------------------------
-- Table `init`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`empresa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`publicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `id_usuarioss` INT NOT NULL,
  `nome_prato` VARCHAR(50) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `cidade-estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_empresa_idx` (`id_empresa` ASC) VISIBLE,
  INDEX `id_usuarioss_idx` (`id_usuarioss` ASC) VISIBLE,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `init`.`empresa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_usuarioss`
    FOREIGN KEY (`id_usuarioss`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`curtidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`curtidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_publicacao` INT NOT NULL,
  `curtidas` ENUM("Like", "Deslike") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_publicacao_idx` (`id_publicacao` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `init`.`publicacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_publicacaoo` INT NOT NULL,
  `foto_perfil` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `data_comentario` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_usuarios_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `id_publicacaoo_idx` (`id_publicacaoo` ASC) VISIBLE,
  CONSTRAINT `id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_publicacaoo`
    FOREIGN KEY (`id_publicacaoo`)
    REFERENCES `init`.`publicacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
