-- MySQL Script generated by MySQL Workbench
-- Mon May 12 08:49:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema init
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema init
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `init` DEFAULT CHARACTER SET utf8 ;
USE `init` ;

-- -----------------------------------------------------
-- Table `init`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `foto` LONGTEXT NOT NULL,
  `nickname` VARCHAR(100) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`empresa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`publicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `id_usuarioss` INT NOT NULL,
  `titulo_prato` VARCHAR(50) NOT NULL,
  `foto` LONGTEXT NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(50) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_empresa_idx` (`empresa_id` ASC) VISIBLE,
  INDEX `id_usuarioss_idx` (`id_usuarioss` ASC) VISIBLE,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `init`.`empresa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_usuarioss`
    FOREIGN KEY (`id_usuarioss`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`curtidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`curtidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_publicacao` INT NOT NULL,
  `curtidas` ENUM("Like", "Deslike") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_publicacao_idx` (`id_publicacao` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `init`.`publicacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  -- Adiciona uma chave única para garantir que não existam combinações duplicadas
  CONSTRAINT `unique_like` UNIQUE (`id_usuario`, `id_publicacao`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `init`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `init`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `id_publicacao` INT NOT NULL,
  `foto_perfil` LONGTEXT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `data_comentario` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_usuarios_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `id_publicacao_idx` (`id_publicacao` ASC) VISIBLE,
  CONSTRAINT `id_usuarios`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `init`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentarios_publicacao`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `init`.`publicacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE OR REPLACE VIEW empresa_com_interacoes AS
SELECT 
  e.id,
  e.nome,
  e.logo,
  COALESCE(SUM(CASE WHEN c.curtidas = 'Like' THEN 1 ELSE 0 END), 0) AS curtidas,
  COALESCE(SUM(CASE WHEN c.curtidas = 'Deslike' THEN 1 ELSE 0 END), 0) AS deslikes
FROM empresa e
LEFT JOIN publicacao p ON e.id = p.empresa_id
LEFT JOIN curtidas c ON p.id = c.id_publicacao
GROUP BY e.id, e.nome, e.logo;